apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento-web
spec:
  selector:
    matchLabels:
      app: magento
      component: web
  template:
    spec:
      containers:
      - name: magento-web
      initContainers:
      - name: wait-for-redis
        image: busybox@sha256:db142d433cdde11f10ae479dbf92f3b13d693fd1c91053da9979728cceb1dc68
        command: ["/bin/sh"]
        args:
          - -c
          - |
            while ! { echo -e '*1\r\n$4\r\nPING\r\n'; sleep 1; } | nc -w1 $(REDIS_CACHE_HOST) $(REDIS_CACHE_PORT)
            do echo "waiting for $(REDIS_CACHE_HOST)"
            sleep 1
            done
        envFrom:
        - configMapRef:
            name: config
        - configMapRef:
            name: additional


---

apiVersion: batch/v1
kind: Job
metadata:
  name: magento-install
spec:
  template:
    spec:
      containers:
      - name: magento-setup
      initContainers:
      - name: wait-for-redis
        image: busybox@sha256:db142d433cdde11f10ae479dbf92f3b13d693fd1c91053da9979728cceb1dc68
        command: ["/bin/sh"]
        args:
          - -c
          - |
            while ! { echo -e '*1\r\n$4\r\nPING\r\n'; sleep 1; } | nc -w1 $(REDIS_CACHE_HOST) $(REDIS_CACHE_PORT)
            do echo "waiting for $(REDIS_CACHE_HOST)"
            sleep 1
            done
        envFrom:
        - configMapRef:
            name: config
        - configMapRef:
            name: additional
