apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: magento-on-kubernetes
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: kiweeteam/magento2
    context: src
    sync:
      infer:
      - 'app/etc/config.php'
      - 'composer.json'
      - 'composer.lock'
    docker:
      dockerfile: Dockerfile
      target: app
  local:
    useBuildkit: true
deploy:
  kustomize:
    paths:
      - overlays/kind
  helm:
    releases:
      - name: ingress-nginx
        remoteChart: nginx-ingress
        repo: https://helm.nginx.com/stable
        setValues:
          controller:
            service:
              type: ClusterIP
      - name: eck-operator
        remoteChart: eck-operator
        repo: https://helm.elastic.co
        version: 1.9.1
portForward:
  - resourceType: Service
    resourceName: ingress-nginx-controller
    port: 443
    localPort: 8443
  - resourceType: Service
    resourceName: ingress-nginx-controller
    port: 80
    localPort: 8080
profiles:
  - name: ci
    patches:
      - op: replace
        path: /deploy/kustomize/paths/0
        value: overlays/test
    build:
      artifacts:
      - image: kiweeteam/magento2-cypress
        context: test/e2e
      - image: kiweeteam/magento2
        context: src
        sync:
          infer:
          - 'app/etc/config.php'
          - 'composer.json'
          - 'composer.lock'
        docker:
          dockerfile: Dockerfile
          target: app
