apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: magento-on-kubernetes
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: kiweeteam/magento2
    context: src
    sync:
      infer:
      - 'app/etc/config.php'
      - 'composer.json'
      - 'composer.lock'
    docker:
      dockerfile: Dockerfile
      target: app
  - image: kiweeteam/magento2-cypress
    context: test/e2e
  local:
    useBuildkit: true
manifests:
  kustomize:
    paths:
      - deploy/overlays/test
deploy:
  statusCheck: true
  tolerateFailuresUntilDeadline: true
  statusCheckDeadlineSeconds: 1200
  kubectl: {}
  helm:
    releases:
      - name: cert-manager
        remoteChart: cert-manager
        repo: https://charts.jetstack.io
        wait: true
        setValues:
          installCRDs: true
          ingressShim:
            defaultIssuerKind: ClusterIssuer
            defaultIssuerName: selfsigned
      - name: ingress-nginx
        remoteChart: oci://ghcr.io/nginxinc/charts/nginx-ingress
        version: 1.2.1
        wait: true
        setValues:
          installCRDs: true
          controller:
            kind: daemonset
            enableSnippets: true
            service:
              enabled: true
              type: ClusterIP
              clusterIP: 10.96.0.2
              httpPort:
                port: 80
              httpsPort:
                port: 443
            ingressClass:
              create: true
              name: nginx
              setAsDefaultIngress: true
      - name: secret-generator
        remoteChart: kubernetes-secret-generator
        repo: https://helm.mittwald.de
        wait: true
portForward:
  - resourceType: Service
    resourceName: ingress-nginx-ingress-controller
    port: 443
    localPort: 443
  - resourceType: Service
    resourceName: ingress-nginx-ingress-controller
    port: 80
    localPort: 80
verify:
- name: magento-e2e
  executionMode:
    kubernetesCluster:
      overrides: '{ "apiVersion": "batch/v1", "spec": { "template": { "spec": { "hostAliases": [ { "ip": "10.96.0.2", "hostnames": [ "magento.test" ] } ] } } } }'
  container:
    name: cypress
    image: kiweeteam/magento2-cypress
    command: ["/bin/sh"]
    env:
      - name: CYPRESS_BASE_URL
        value: https://magento.test/
    args:
    - -c
    - |
      curl \
        -kILSs \
        -X GET \
        --fail \
        --retry 9 \
        --retry-all-errors \
        $CYPRESS_BASE_URL/simple-product-1.html

      npm test
