apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: step-3

bases:
  - ../step-2
  - ../bases/redis

resources:
  - hpa/magento-php.yaml
  - hpa/magento-web.yaml

patchesStrategicMerge:
  - patches/wait-for-redis.yaml

configMapGenerator:
- name: additional
  behavior: merge
  envs:
  - config/additional.env
