---
apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: "StringSecret"
metadata:
  name: magento-admin
spec:
  forceRegenerate: false
  data:
    ADMIN_URI: "admin"
    ADMIN_EMAIL: "admin@example.com"
    ADMIN_FIRSTNAME: "Jane"
    ADMIN_LASTNAME: "Doe"
    ADMIN_USER: "admin"
  fields:
    - fieldName: "ADMIN_PASSWORD"
      encoding: "base32"
      length: "20"
