apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: app

resources:
- php.yaml
- web.yaml
- ingress/main.yaml
- cron/magento.yaml
- jobs/install.yaml
- jobs/unpack.yaml
- pvc/media.yaml
- pvc/static.yaml

configMapGenerator:
- name: nginx
  files:
  - config/nginx/conf.d/default.conf
  - config/nginx/magento2.conf
- name: config
  envs:
  - config/common.env
- name: additional
  envs:
  - config/additional.env
