apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: app

resources:
- magento-web.yaml
- credentials.yaml
- ingress/main.yaml
- cron/magento.yaml
- jobs/install.yaml
- pvc/media.yaml

configMapGenerator:
- name: nginx
  files:
  - config/nginx/conf.d/default.conf
  - config/nginx/magento2.conf
- name: config
  envs:
  - config/common.env
- name: additional
  envs:
  - config/additional.env
