apiVersion: batch/v1
kind: Job
metadata:
  name: magento-install
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      name: install
      labels:
        app: magento-install
        k8s-app: magento
    spec:
      initContainers:
      - name: wait-for-db
        image: kiweeteam/magento2:2.4.6-p3-1@sha256:7915c27b0fbc595b6fcb357de1923cca27e104f06b9e14b799eaed7a8585fc3a
        command:
          - /bin/bash
        args:
        - -c
        - |
          while ! nc -z $DB_HOST 3306;
          do
            echo "Waiting for database...";
            sleep 1;
          done;
          echo "Database found";
        envFrom:
        - configMapRef:
            name: config
        - configMapRef:
            name: additional
      - name: wait-for-elasticsearch
        image: curlimages/curl:8.4.0@sha256:4a3396ae573c44932d06ba33f8696db4429c419da87cbdc82965ee96a37dd0af
        command: ["/bin/sh"]
        args:
        - -c
        - |
          while ! curl -kILSs --fail -XGET \
            $(CONFIG__DEFAULT__CATALOG__SEARCH__ELASTICSEARCH7_SERVER_HOSTNAME):$(CONFIG__DEFAULT__CATALOG__SEARCH__ELASTICSEARCH7_SERVER_PORT)
          do echo "waiting for $(CONFIG__DEFAULT__CATALOG__SEARCH__ELASTICSEARCH7_SERVER_HOSTNAME):$(CONFIG__DEFAULT__CATALOG__SEARCH__ELASTICSEARCH7_SERVER_PORT)"
          sleep 1
          done
        envFrom:
        - configMapRef:
            name: config
        - configMapRef:
            name: additional
      containers:
      - name: magento-setup
        image: kiweeteam/magento2:2.4.6-p3-1@sha256:7915c27b0fbc595b6fcb357de1923cca27e104f06b9e14b799eaed7a8585fc3a
        command:
          - /bin/bash
        args:
        - -c
        - |
          set -o errexit
          ./bin/install.sh
          php bin/magento setup:perf:generate-fixtures setup/performance-toolkit/profiles/ce/mok.xml
          magerun --no-interaction index:list | awk '{print $2}' | tail -n+4 | xargs -I{} magerun --no-interaction index:set-mode schedule {}
          magerun --no-interaction index:reset
          magerun --no-interaction cache:flush
        envFrom:
        - configMapRef:
            name: config
        - configMapRef:
            name: additional
        volumeMounts:
        - mountPath: /var/www/html/pub/media
          name: media
        imagePullPolicy: IfNotPresent
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media
      restartPolicy: OnFailure
