apiVersion: batch/v1
kind: Job
metadata:
  name: magento-install
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      name: install
      labels:
        app: magento
        component: install
    spec:
      initContainers:
      - name: set-volume-ownership
        image: busybox@sha256:2919d0172f7524b2d8df9e50066a682669e6d170ac0f6a49676d54358fe970b5
        command:
        - /bin/sh
        args:
        - -c
        - chown -R 33:33 /var/www/html/pub/media
        volumeMounts:
        - mountPath: /var/www/html/pub/media
          name: media
          subPath: media
      - name: wait-for-db
        image: kiweeteam/magento2:2.4.6-p7-2@sha256:76d56f42a859ec70e193257c5c22992efb61a1b818f217f316fc9d0899a8a30a
        command:
          - /bin/bash
        args:
        - -c
        - |
          while ! nc -z $DB_HOST 3306;
          do
            echo "Waiting for database...";
            sleep 1;
          done;
          echo "Database found";
        env:
        - name: DB_HOST
          value: db
        envFrom:
        - configMapRef:
            name: config
        - configMapRef:
            name: additional
      - name: wait-for-elasticsearch
        image: curlimages/curl:8.11.1@sha256:c1fe1679c34d9784c1b0d1e5f62ac0a79fca01fb6377cdd33e90473c6f9f9a69
        command: ["/bin/sh"]
        args:
        - -c
        - |
          while ! curl -kILSs --fail -XGET \
            $(CONFIG__DEFAULT__CATALOG__SEARCH__ELASTICSEARCH7_SERVER_HOSTNAME):$(CONFIG__DEFAULT__CATALOG__SEARCH__ELASTICSEARCH7_SERVER_PORT)
          do echo "waiting for $(CONFIG__DEFAULT__CATALOG__SEARCH__ELASTICSEARCH7_SERVER_HOSTNAME):$(CONFIG__DEFAULT__CATALOG__SEARCH__ELASTICSEARCH7_SERVER_PORT)"
          sleep 1
          done
        envFrom:
        - configMapRef:
            name: config
        - configMapRef:
            name: additional
      containers:
      - name: magento-setup
        image: kiweeteam/magento2:2.4.6-p7-2@sha256:76d56f42a859ec70e193257c5c22992efb61a1b818f217f316fc9d0899a8a30a
        command:
          - /bin/bash
        args:
        - -c
        - |
          set -o errexit
          ./bin/install.sh
          php bin/magento setup:perf:generate-fixtures setup/performance-toolkit/profiles/ce/mok.xml
          magerun --no-interaction index:list | awk '{print $2}' | tail -n+4 | xargs -I{} magerun --no-interaction index:set-mode schedule {}
          magerun --no-interaction index:reset
          magerun --no-interaction cache:flush
        env:
        - name: DB_HOST
          value: db
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: MYSQL_DATABASE
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: MYSQL_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: MYSQL_PASSWORD
        envFrom:
        - configMapRef:
            name: config
        - configMapRef:
            name: additional
        - secretRef:
            name: magento-admin
        volumeMounts:
        - mountPath: /var/www/html/pub/media
          name: media
          subPath: media
        imagePullPolicy: IfNotPresent
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media
      restartPolicy: OnFailure
