bases:
  - ../../deploy/step-4

patchesStrategicMerge:
  - patches/pvc.yaml

configMapGenerator:
- name: config
  behavior: merge
  envs:
  - patches/common.env

patchesJson6902:
- path: patches/ingress.json
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: main
