apiVersion: v1
kind: Service
metadata:
  name: varnish
  labels:
    app: varnish
spec:
  selector:
    app: varnish
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  - name: proxy
    port: 8081
    protocol: TCP
    targetPort: proxy
  - name: admin
    port: 6081
    protocol: TCP
    targetPort: admin

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish
spec:
  selector:
    matchLabels:
      app: varnish
  replicas: 1
  template:
    metadata:
      labels:
        app: varnish
    spec:
      containers:
      - image: varnish:7.6@sha256:8db4c6e34f4b9aa82b05154d2a14cd25f300ae7d41afd121211080cf59cb7823
        name: varnish
        command: ["/bin/sh"]
        args:
          - -c
          - |
            varnishd -a :8080 -a :8081,PROXY -a :6081 -f /etc/varnish/default.vcl -s default,512M;
            varnishncsa -F '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-agent}i" %{Varnish:handling}x'
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: proxy
          containerPort: 8081
          protocol: TCP
        - name: admin
          containerPort: 6081
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 512Mi
        env:
        - name: VARNISH_BACKEND_HOST
          value: web
        - name: VARNISH_BACKEND_PORT
          value: "80"
        volumeMounts:
        - name: config
          mountPath: /etc/varnish/default.vcl
          subPath: default.vcl
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: varnish
