apiVersion: v1
kind: Service
metadata:
  name: varnish
  labels:
    app: varnish
spec:
  selector:
    app: varnish
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: proxy
    port: 6091
    protocol: TCP
    targetPort: 6091

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish
spec:
  selector:
    matchLabels:
      app: varnish
  replicas: 1
  template:
    metadata:
      labels:
        app: varnish
    spec:
      containers:
      - image: varnish:7.4@sha256:1ac252387dfde1107516d8de9a4f29e70a2730bb40902ab042b92025e1fb534c
        name: varnish
        command: ["/bin/sh"]
        args:
          - -c
          - |
            varnishd -a :8080 -a :6091 -f /etc/varnish/default.vcl -s default,512M;
            varnishncsa -F '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-agent}i" %{Varnish:handling}x'
        ports:
        - containerPort: 8080
        - containerPort: 6091
        resources:
          requests:
            cpu: 50m
            memory: 512Mi
        env:
        - name: VARNISH_BACKEND_HOST
          value: web
        - name: VARNISH_BACKEND_PORT
          value: "80"
        volumeMounts:
        - name: config
          mountPath: /etc/varnish/default.vcl
          subPath: default.vcl
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: varnish
