apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    k8s-app: magento
spec:
  selector:
    app: elasticsearch
  ports:
  - name: elasticsearch
    port: 9200
    protocol: TCP
    targetPort: 9200

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  serviceName: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
        k8s-app: magento
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.17.13@sha256:7a32c0bd5399222dfe7bb85327b4c05226b46027288ea266193e2193ef076b14
        imagePullPolicy: IfNotPresent
        env:
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx256m
        - name: discovery.seed_hosts
          value: elasticsearch-0.elasticsearch
        - name: cluster.initial_master_nodes
          value: elasticsearch-0
        - name: xpack.security.enabled
          value: "false"
        - name: ingest.geoip.downloader.enabled
          value: "false"
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
