apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - name: elasticsearch
    port: 9200
    protocol: TCP
    targetPort: 9200

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  serviceName: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
      - name: set-volume-ownership
        image: busybox
        command:
        - /bin/sh
        args:
        - -c
        - chown -R 1000:1000 /usr/share/elasticsearch/data
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
          subPath: data
      containers:
      - name: elasticsearch
        image: elasticsearch:7.17.18@sha256:5f99f2f450ca38aff315a4a8849e892934cafef0aee5e6ab5d894ede97a02ca9
        imagePullPolicy: IfNotPresent
        env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: discovery.seed_hosts
          value: elasticsearch-0.elasticsearch
        - name: cluster.initial_master_nodes
          value: elasticsearch-0
        - name: xpack.security.enabled
          value: "false"
        - name: ingest.geoip.downloader.enabled
          value: "false"
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
          subPath: data
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 500m
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
