apiVersion: batch/v1
kind: Job
metadata:
  name: magento-install
spec:
  template:
    spec:
      containers:
      - name: magento-setup
      initContainers:
      - name: wait-for-redis
        image: busybox
        command: ["/bin/sh"]
        args:
          - -c
          - |
            while ! { echo -e '*1\r\n$4\r\nPING\r\n'; sleep 1; } | nc -w1 $(REDIS_CACHE_HOST) $(REDIS_CACHE_PORT)
            do echo "waiting for $(REDIS_CACHE_HOST)"
            sleep 1
            done
        envFrom:
        - configMapRef:
            name: config
        - configMapRef:
            name: additional
