apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: step-4



configMapGenerator:
- behavior: merge
  envs:
  - config/additional.env
  name: additional
resources:
- ../step-3
- ../bases/varnish
patches:
- path: patches/ingress.json
  target:
    group: networking.k8s.io
    kind: Ingress
    name: main
    version: v1
