apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: step-4

bases:
  - ../step-3
  - ../bases/varnish

patchesJson6902:
- path: patch/ingress.json
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: main

configMapGenerator:
- name: additional
  behavior: merge
  envs:
  - config/additional.env
