---
apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: "StringSecret"
metadata:
  name: database-credentials
spec:
  forceRegenerate: false
  data:
    MYSQL_USER: "magento"
    MYSQL_DATABASE: "magento"
  fields:
    - fieldName: "MYSQL_PASSWORD"
      encoding: "base64"
      length: "20"
    - fieldName: "MYSQL_ROOT_PASSWORD"
      encoding: "base64"
      length: "20"
