apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
    k8s-app: magento
spec:
  selector:
    app: db
  ports:
  - name: db
    port: 3306

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  serviceName: db
  template:
    metadata:
      labels:
        app: db
        k8s-app: magento
    spec:
      initContainers:
      - name: set-volume-ownership
        image: busybox@sha256:37f7b378a29ceb4c551b1b5582e27747b855bbfaa73fa11914fe0df028dc581f
        command:
        - /bin/sh
        args:
        - -c
        - chown -R 1001:1001 /var/lib/mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
          subPath: mysql
      containers:
      - name: db
        image: percona:8.0@sha256:430156f059298825eacfd85c08497cdd73c4b7bc7c620f51e5a53ba8bd5018b1
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
          subPath: mysql
        - mountPath: /etc/my.cnf.d/magento.cnf
          name: mycnf
          subPath: my.cnf
        env:
        - name: DB_HOST
          value: db
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: MYSQL_DATABASE
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: MYSQL_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: MYSQL_USER
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: MYSQL_ROOT_PASSWORD
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      volumes:
      - name: mycnf
        configMap:
          name: mycnf
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
