apiVersion: batch/v1
kind: CronJob
metadata:
  name: magento-cron
spec:
  schedule: '* * * * *'
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          labels:
            app: magento
            component: cron
        spec:
          initContainers:
          - name: wait-for-web
            image: curlimages/curl:8.11.0@sha256:83a505ba2ba62f208ed6e410c268b7b9aa48f0f7b403c8108b9773b44199dbba
            command: ["/bin/sh"]
            args:
            - -c
            - |
              while ! curl -kILSs --fail -XGET \
                -H "Host: $(CONFIG__DEFAULT__WEB__COOKIE__COOKIE_DOMAIN)" \
                $(MAGENTO_WEB_SERVICE_HOST):$(MAGENTO_WEB_SERVICE_PORT_HTTP)/health_check.php
              do echo "waiting for $(MAGENTO_WEB_SERVICE_HOST)"
              sleep 1
              done
            envFrom:
            - configMapRef:
                name: config
          containers:
          - name: magento-cron
            image: kiweeteam/magento2:2.4.6-p7-2@sha256:76d56f42a859ec70e193257c5c22992efb61a1b818f217f316fc9d0899a8a30a
            command: ["/bin/sh"]
            args:
            - -c
            - |
              php bin/magento cron:run
            env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: MYSQL_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: MYSQL_PASSWORD
            envFrom:
            - configMapRef:
                name: config
            - configMapRef:
                name: additional
            resources:
              limits:
                cpu: 500m
                memory: 4Gi
              requests:
                cpu: 50m
                memory: 1Gi
          restartPolicy: Never
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  failedJobsHistoryLimit: 20
  successfulJobsHistoryLimit: 5
