apiVersion: batch/v1
kind: CronJob
metadata:
  name: magento-cron
spec:
  schedule: '* * * * *'
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          labels:
            app: magento
            component: cron
        spec:
          initContainers:
          - name: wait-for-web
            image: curlimages/curl:8.5.0@sha256:4bfa3e2c0164fb103fb9bfd4dc956facce32b6c5d47cc09fcec883ce9535d5ac
            command: ["/bin/sh"]
            args:
            - -c
            - |
              while ! curl -kILSs --fail -XGET \
                -H "Host: $(CONFIG__DEFAULT__WEB__COOKIE__COOKIE_DOMAIN)" \
                $(MAGENTO_WEB_SERVICE_HOST):$(MAGENTO_WEB_SERVICE_PORT_HTTP)/health_check.php
              do echo "waiting for $(MAGENTO_WEB_SERVICE_HOST)"
              sleep 1
              done
            envFrom:
            - configMapRef:
                name: config
          containers:
          - name: magento-cron
            image: kiweeteam/magento2:2.4.6-p3-1@sha256:7915c27b0fbc595b6fcb357de1923cca27e104f06b9e14b799eaed7a8585fc3a
            command: ["/bin/sh"]
            args:
            - -c
            - |
              php bin/magento cron:run
            env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: MYSQL_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: MYSQL_PASSWORD
            envFrom:
            - configMapRef:
                name: config
            - configMapRef:
                name: additional
            resources:
              limits:
                cpu: 500m
                memory: 4Gi
              requests:
                cpu: 50m
                memory: 1Gi
          restartPolicy: Never
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  failedJobsHistoryLimit: 20
  successfulJobsHistoryLimit: 5
