apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: step-2

bases:
  - ../step-1
  - ../bases/elasticsearch

patchesStrategicMerge:
  - patches/wait-for-elasticsearch.yaml

configMapGenerator:
- name: additional
  behavior: merge
  envs:
  - config/additional.env
