apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: step-2



configMapGenerator:
- behavior: merge
  envs:
  - config/additional.env
  name: additional
resources:
- ../step-1
- ../bases/elasticsearch
patches:
- path: patches/wait-for-elasticsearch-magento-web.yaml
- path: patches/wait-for-elasticsearch-magento-install.yaml
