name: Test
run-name: Test
on: [push]
jobs:
  test:
    strategy:
      matrix:
        k8s-version: [v1.22.17, v1.23.17, v1.24.12]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          node_image: kindest/node:${{ matrix.k8s-version }}
      - uses: alexellis/setup-arkade@v2
      - uses: alexellis/arkade-get@master
        with:
          kubectl: latest
          kustomize: latest
          helm: latest
      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
          skaffold version
      - name: Cache skaffold image builds & config
        uses: actions/cache@v2
        with:
          path: ~/.skaffold/
          key: fixed-${{ github.sha }}
      - name: Test
        run: |
          skaffold run --profile="ci"
          kubectl wait --timeout=60s --for=condition=Ready pod --selector=job-name=magento-install || kubectl wait --timeout=60s --for=condition=complete pod --selector=job-name=magento-install
          kubectl logs -f job/magento-install --all-containers
          kubectl wait --timeout=60s --for=condition=Ready pod --selector=job-name=cypress || kubectl wait --timeout=60s --for=condition=complete pod --selector=job-name=cypress
          kubectl logs -f job/cypress --all-containers
          kubectl wait --timeout=600s --for=condition=complete pod --selector=job-name=cypress
          kubectl logs -f job/cypress --all-containers
