name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        k8s-version: [v1.25.11, v1.26.6, v1.27.3]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.8.0
        with:
          node_image: kindest/node:${{ matrix.k8s-version }}
      - uses: alexellis/setup-arkade@v3
      - uses: alexellis/arkade-get@master
        with:
          kubectl: latest
          kustomize: latest
          helm: latest
      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
          skaffold version
      - name: Cache skaffold image builds & config
        uses: actions/cache@v3
        with:
          path: ~/.skaffold/
          key: fixed-${{ github.sha }}
      - name: Deploy Magento
        run: |
          skaffold run --profile="ci" --status-check=false
          kubectl wait --timeout=0 --for=condition=complete job/magento-install || \
          kubectl wait --timeout=300s --for=condition=Ready pod --selector=job-name=magento-install
          kubectl logs -f job/magento-install --all-containers
          kubectl wait --timeout=60s --for=condition=complete job/magento-install
      - name: Test
        run: |
          kubectl wait --timeout=0 --for=condition=complete job/cypress || \
          kubectl wait --timeout=120s --for=condition=Ready pod --selector=job-name=cypress
          kubectl logs -f job/cypress
          kubectl wait --timeout=300s --for=condition=complete job/cypress
