name: CI
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    name: deploy magento to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      run:
        make minikube
        
    - name: Deploy to minikube
      run:
        make step-4
     
