name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        k8s-version: [v1.26.6, v1.27.3, v1.28.0]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
        with:
          node_image: kindest/node:${{ matrix.k8s-version }}
      - uses: alexellis/setup-arkade@b1816384b2260cfd2c023c6798d26075786cfc7f # v3
      - uses: alexellis/arkade-get@master
        with:
          kubectl: latest
          kustomize: latest
          helm: latest
      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
          skaffold version
      - name: Cache skaffold image builds & config
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        with:
          path: ~/.skaffold/
          key: fixed-${{ github.sha }}
      # https://kind.sigs.k8s.io/docs/user/known-issues/#apparmor
      - name: Disable AppArmor for MySQL
        run: |
          set -x
          sudo apt-get install apparmor-profiles
          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: Deploy Magento
        run: |
          skaffold run --profile="ci" --status-check=false
          kubectl wait --timeout=0 --for=condition=complete job/magento-install || \
          kubectl wait --timeout=300s --for=condition=Ready pod --selector=job-name=magento-install
          kubectl logs -f job/magento-install --all-containers
          kubectl wait --timeout=60s --for=condition=complete job/magento-install
      - name: Test
        run: |
          kubectl wait --timeout=0 --for=condition=complete job/cypress || \
          kubectl wait --timeout=120s --for=condition=Ready pod --selector=job-name=cypress
          kubectl logs -f job/cypress
          kubectl wait --timeout=300s --for=condition=complete job/cypress
