name: CI
on: [push]
jobs:
  job1:
    runs-on: self-hosted
    name: deploy magento to minikube local 3
    steps:
    - name: Deploy to minikube
      run:
        make step-1
    - name: Display pods
      run:
        kubectl get pods
     
