name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        k8s-version: [v1.27.3, v1.28.0, v1.29.0]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@99576bfa6ddf9a8e612d83b513da5a75875caced # v1.9.0
        with:
          node_image: kindest/node:${{ matrix.k8s-version }}
      - uses: alexellis/setup-arkade@b1816384b2260cfd2c023c6798d26075786cfc7f # v3
      - uses: alexellis/arkade-get@master
        with:
          kubectl: latest
          kustomize: latest
          helm: latest
      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
          skaffold version
      - name: Cache skaffold image builds & config
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: ~/.skaffold/
          key: fixed-${{ github.sha }}
      # https://kind.sigs.k8s.io/docs/user/known-issues/#apparmor
      - name: Disable AppArmor for MySQL
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install apparmor-profiles
          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: Build
        run: |
          skaffold build --file-output=build.artifacts
      - name: Run
        run: |
          skaffold run --status-check=true
      - name: Test
        run: |
          skaffold verify -a build.artifacts
